Conditional VAEのPostorierEncoderを追加する
matsuo-group24-PinkTrombone/SpeechGeneration pull request #14
Opened 2023-01-13 03:50 UTC by takeshun256

## 概要

Conditional VAE の PostorierEncoder に関する以下のコードを、ESPnetのコードから移植しました。
- PostorierEncoderを動かすためのライブラリ
- PostorierEncoderを動かすために必要なコンポーネントのコード
- 追加したコンポーネントのテストコード

## 変更内容

- PostorierEncoderに関するモデルやレイヤーを `src` 下に追加
- PostorierEncoder に関するモデルやレイヤーのテストコードを `tests` 下へ追加
- テストコードを実行するために必要なライブラリを `pyproject.toml` へ記載
- 環境設定に関するファイルがpushされないようにするために、`.gitignore` に `.devcontainer/` と `.vscode/` を記載

## 影響範囲

- 環境設定
  - pyproject.toml
  - .gitignore
- PostrierEncoer  の実装
  - src/models/components
  - src/utils
- PostrierEncoer  の実装で追加したコンポーネントのテストコード
  - tests/models/components
  - tests/models/utils

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を `pytest`または `make test`コマンドでローカルにテストしましたか?
- [x] `pre-commit run -a` または`make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足
`tests/posterior_encoder.py` は、ESPnetにあるコードを用いず、別途追加しているため、テストコードとして粗がある可能性がある。

2023-01-13 06:38 UTC, Geson-anko commented
@seichi042I stftやmelスペクトログラムへの変換処理`src/utls/layers/log_mel.py`などは今回の実験の処理に使用しないことが想定されるため、メイン処理に使わないという内容をコメントとしてファイルに記述するようにしてください。  
もしテスト時のみ使われるだけであれば、`tests/helpers`フォルダへ移動し、そこから使用することを推奨します。

2023-01-13 07:30 UTC, Geson-anko requested changes
実装ありがとうございます。初めてなので色々指摘が多いかもしれませんが、よろしくお願いします。

### 改善点
- 一つのコミットの単位が大きすぎます。1コミットは極力一つのファイル変更に対して行い、コミットメッセージはその内容が簡潔にわかるものにしてください。
- 一つのプルリクエストとして大きすぎるため、今回の機能実装において必要なファイルのみをコミットしてください。
- Posterior Encoderに直接的な関係がなく、不必要と思われるファイルがあります。それらの必要性や依存関係(テスト時のみに必要なだけ、など)を精査し、適切な位置にファイルを配置、作成してください。
    - `src/utils/layers/log_mel.py`(pynktrombonegymの内部に存在)
    - `src/utils/stft.py` (pynktrombonegymの内部に存在)
    - feats_extract/* (必要性を理解しきれなかった)
- ブランチ名を具体的な機能名にしてください。`feature/seichi`ではなく`feature/posterior_encoder_vits`というような形にしてください。（次回で構いません)

2023-01-13 07:30 UTC, Geson-anko commented on tests/models/components/wavenet/test_wavenet.py
> +        out.size(1) == args["skip_channels"]
assertをつけてください。pytestでエラー検出が可能になります。
```suggestion
    if args["use_last_conv"]:
        assert out.size(1) == args["out_channels"]
    else:
        assert out.size(1) == args["skip_channels"]
```

2023-01-14 12:04 UTC, seichi042I commented
> 実装ありがとうございます。初めてなので色々指摘が多いかもしれませんが、よろしくお願いします。
> 
> ### 改善点
> * 一つのコミットの単位が大きすぎます。1コミットは極力一つのファイル変更に対して行い、コミットメッセージはその内容が簡潔にわかるものにしてください。
> * 一つのプルリクエストとして大きすぎるため、今回の機能実装において必要なファイルのみをコミットしてください。
> * Posterior Encoderに直接的な関係がなく、不必要と思われるファイルがあります。それらの必要性や依存関係(テスト時のみに必要なだけ、など)を精査し、適切な位置にファイルを配置、作成してください。
>   
>   * `src/utils/layers/log_mel.py`(pynktrombonegymの内部に存在)
>   * `src/utils/stft.py` (pynktrombonegymの内部に存在)
>   * feats_extract/* (必要性を理解しきれなかった)
> * ブランチ名を具体的な機能名にしてください。`feature/seichi`ではなく`feature/posterior_encoder_vits`というような形にしてください。（次回で構いません)

相対importとlogmel関連のファイル配置を修正しました。

2023-01-15 06:07 UTC, Geson-anko requested changes
### ファイル追加リクエスト  
Pythonのソースファイルを配置する場合は `__init__.py`を必ず作成してください。  
https://docs.python.org/ja/3/tutorial/modules.html?highlight=import  
- tests/helpers/__init__.py
- tests/helpers/layers/__init__.py

###  修正リクエスト
- src/models/components/posterior_encoder.py --> src/models/components/posterior_encoder **_vits** .py 
- tests/models/components/test_posterior_encoder.py -->  tests/models/components/test_posterior_encoder **_vits** .py

2023-01-15 08:13 UTC, cehl-kurage approved these changes
データの流れについては問題なかったと思います

2023-01-17 02:29 UTC, Geson-anko approved these changes

2023-01-17 11:19 UTC, Geson-anko approved these changes
@takeshun256 細かいところは修正しました。マージお願いします。

2023-01-17 11:58 UTC, merged