環境作成関数make_envの実装
matsuo-group24-PinkTrombone/SpeechGeneration pull request #59
Opened 2023-01-28 17:41 UTC by takeshun256

## 概要

#51 環境作成関数make_envの実装ブランチです。

## 変更内容

- src/env/make_env.py
- tests/src/env/test_make_env.py

## 影響範囲

上記ファイル

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を `pytest`または `make test`コマンドでローカルにテストしましたか?
- [ ] `pre-commit run -a` または`make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-01-29 10:43 UTC, Geson-anko requested changes
修正点がとても多くなってしまいましたが、一つずつ直していきましょう。

2023-01-29 10:43 UTC, Geson-anko commented on src/env/make_env.py
> +from pynktrombonegym.wrappers.log1p_mel_spectrogram import Log1pMelSpectrogram
これでいけます。
```suggestion
from pynktrombonegym.wrappers import ActionByAcceleration, Log1pMelSpectrogram
```

2023-01-29 10:43 UTC, Geson-anko commented on src/env/make_env.py
> +             sample_rate: int = 44100, n_mels: int = 80, dtype: Any = np.float32) -> gym.Env:
Noneをデフォルトの値にすることは避けましょう。どうしてもデフォルト値に内部処理が必要な値のみ使用しましょう。(NULLやnullptrにより数々の不具合が引き起こされてきました。)  
docstringの修正もお願いします。
```suggestion
def make_env(dataset_dirs: List[Any], file_exts: List[str] = ["wav"], 
             action_scaler: Optional[float] = None, low: float = -1.0, high: float = 1.0, 
             sample_rate: int = 44100, n_mels: int = 80, dtype: Any = np.float32) -> gym.Env:
```

2023-01-29 10:43 UTC, Geson-anko commented on src/env/make_env.py
> +    file_exts = file_exts or [".wav"]
```suggestion
```

2023-01-29 10:43 UTC, Geson-anko commented on src/env/make_env.py
> +    base_env = Log1pMelSpectrogram(files, **base_env_kwargs)
```suggestion
    base_env = Log1pMelSpectrogram(files, sample_rate=sample_rate, n_mels=n_mels, dtype=dtype)
```

2023-01-29 10:43 UTC, Geson-anko commented on src/env/make_env.py
> +def apply_wrappers(env: gym.Env, action_scaler: float = 1.0, low: float = 10.0, high: float = 10.0) -> gym.Env:
デフォルト引数の定義箇所は一つにしましょう。コードの修正を楽にすることができます。
```suggestion
def apply_wrappers(env: gym.Env, action_scaler: float, low: float, high: float) -> gym.Env:
```

2023-01-29 10:43 UTC, Geson-anko commented on src/env/make_env.py
> +    env = apply_wrappers(base_env, **apply_wrappers_kwargs)
action_scalerは次のように指定してください。（加速度の積分計算に使用される値で、デフォルト値の設定は現実時間のスケールにするとうまくいくことがわかっています。)
```suggestion
    if action_scaler is None:
        action_scaler = base_env.generate_chunk / base_env.sample_rate
    env = apply_wrappers(base_env, action_scaler, low, high)
```

2023-01-29 10:43 UTC, Geson-anko commented on src/env/make_env.py
> +def create_file_list(dataset_dirs: List[Any], file_exts: Optional[List[str]] = None) -> List[str]:
```suggestion
def create_file_list(dataset_dirs: List[Any], file_exts: List[str]) -> List[str]:
```

2023-01-29 10:43 UTC, Geson-anko commented on src/env/make_env.py
> +        file_exts = [".wav"]
```suggestion
```

2023-01-29 10:43 UTC, Geson-anko commented on src/env/make_env.py
> +        return files
```suggestion
```

2023-01-29 10:43 UTC, Geson-anko commented on src/env/make_env.py
> +            print(f"{dataset_dir} is not a directory.")
`dataset_dir`にディレクトリ以外のものが入ってきた場合は、例外を送信しましょう。
```suggestion
        else:
            raise ValueError(f"{dataset_dir} is not a directory or does not exist.")
```

2023-01-29 10:43 UTC, Geson-anko commented on tests/env/test_make_env.py
> +    )
OmegaConfを使う意図がわからなかったのと、できるだけテストは簡潔にしてほしいです。
```suggestion
    configs = {
            "dataset_dirs": sample_target_sound_dir_paths,
            "file_exts": [".wav"],
            "action_scaler": 1.0,
            "low": -10.0,
            "high": 10.0,
    }
```

2023-01-29 10:43 UTC, Geson-anko commented on tests/env/test_make_env.py
> +sample_target_sound_dir_paths = list(glob.glob("data/**/", recursive=True))
重い処理を走らせないように修正お願いします。('recursive`は処理が非常に重くなる可能性があるためおすすめしません)
```suggestion
sample_target_sound_dir_paths = ["data/sample_target_sounds/"]
```

2023-01-29 16:21 UTC, takeshun256 commented
テストコード書き終わりました！
テストコードについて、それぞれ以下の注意点があります。
1. `test__init__()` は、それぞれのラッパークラスの方で  `test__init__()` のテストを実施しているため、出力の型のみ確認にしています。
2. `test_create_file_list()` は、`create_file_list()` 内で `os.path.isdir(dataset_dir)` を実行しており、テストするには実際のディレクトリとファイルが必要であるため、`tempfile` ライブラリを使用しています。
3. `test_apply_wrappers()`  は、それぞれのラッパーが想定通りにラップされているかを確認するのが不可能であるため、出力の型のみ確認しています。

2023-01-30 03:33 UTC, Geson-anko commented
@takeshun256 
機能追加のブランチの名前に`feature/`を付けることを忘れないように気をつけてください。
また、コードを書くときには、簡潔に、目的の機能だけを素直に実装してください。関数それ自体を単純にすることで、バグを防止したり、リファクタリング、不具合の修正が用意になります。
初めてなことが多いとは思いますが、頑張っていきましょう！

2023-01-30 03:34 UTC, merged