Trainerクラスのテスト
matsuo-group24-PinkTrombone/SpeechGeneration pull request #63
Opened 2023-01-29 13:45 UTC by cehl-kurage

## 概要
Trainerクラスに関してテストを行います
詳細: #62 

## 変更内容

## 影響範囲

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を `pytest`または `make test`コマンドでローカルにテストしましたか?
- [ ] `pre-commit run -a` または`make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-02-02 09:53 UTC, cehl-kurage commented on src/trainer.py
> +                        save_path = f"{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.ckpt"
@Geson-anko 
質問2のチェックポイントの保存場所です
チェックポイントを指定しない場合このような保存先になってしまっています

提案なのですが、チェックポイントにはデフォルト引数Noneを設定せず、指定しないと必ずエラーが出る設計にしてはどうでしょうか？

2023-02-02 09:55 UTC, cehl-kurage commented on src/models/dreamer.py
> +            rec_generated_sound_loss += F.mse_loss(gened_sound.cpu(), rec_gened_sound.cpu())
質問1のlossの計算部分です

2023-02-02 12:58 UTC, Geson-anko commented
@cehl-kurage 
質問1についてなのですが、dummy_classesを相当書き直さないといけないかもです。要するに、適当にダミーのアウトプットを`randn`とかで作ってしまっている以上cpu上にテンソルが生成されてしまうことが問題です。ダミークラスの内部レイヤーと入力テンソルを作用させるように書き直さないとちゃんとテストできません...
これは私のミスです。

2023-02-02 13:17 UTC, Geson-anko commented
@cehl-kurage テスト時にckptファイルが/workspaceに出力されてしまうので、`/tmp`ディレクトリに出力するか、`logs/`の中に保存してください。

2023-02-02 13:48 UTC, Geson-anko approved these changes
ここまで書かないと見えないんですね...

2023-02-03 03:47 UTC, Geson-anko requested changes
お疲れ様です。複雑なファイルのテストお疲れ様でした。いくつか修正したのちに、マージします。

2023-02-03 03:47 UTC, Geson-anko commented on src/models/dreamer.py
> +                [old_hiddens[indices[i] + 1, i] if d else hidden[i] for i, d in enumerate(is_done)]
controller_hiddenは`zeros_like`で初期化し、hiddenは`old_hiddens[indices[I] + 1, i]`を`torch.as_tensor`でテンソル化とdevice, dtype移動を行ってください。

2023-02-03 03:47 UTC, Geson-anko commented on src/trainer.py
> +            f"{datetime.now().strftime('%Y-%m-%d_%H-%M-%S')}.ckpt",
ファイル名はエピソード数やステップ数を記述することが適切です。その方が実験時のタイミングを一目で知ることができるためです。
```suggestion
            f"episode-{episode}_step-{current_step}.ckpt",
```

2023-02-03 03:47 UTC, Geson-anko commented on tests/test_trainer.py
> +    p_dir = NamedTemporaryFile().name
一時ディレクトリは`TemporaryDirectory`を使用します。
```suggestion
    p_dir = TemporaryDirectory().name
```
https://docs.python.org/ja/3/library/tempfile.html#tempfile.TemporaryDirectory

2023-02-03 05:47 UTC, Geson-anko approved these changes
お疲れさまでした。あとはコンソールへのlogging処理をすれば終わりです！

2023-02-03 05:47 UTC, merged