Fix/#88linear to linear layers
matsuo-group24-PinkTrombone/SpeechGeneration pull request #89
Opened 2023-02-08 10:23 UTC by seichi042I

## 概要
#88 
各モジュールのlinearをLinearLayersに変更

## 変更内容
- src/models/components/controller.pyを変更
- src/models/components/observation_auto_encoder.pyを変更
- src/models/components/prior_encoder.pyを変更

## 影響範囲
上記のファイルをimportしているファイル
- dreamer.py
- agent.py
- world.py

## Submit前の確認項目

- [x] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [x] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [x] この PR で導入されたすべての変更点をリストアップしましたか?
- [x] PR を `pytest`または `make test`コマンドでローカルにテストしましたか?
- [x] `pre-commit run -a` または`make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足
変更後，すべてのテストの動作確認済み

2023-02-08 12:39 UTC, Geson-anko requested changes
お疲れ様です。いい感じに実装出来てきましたね。
LinearLayersを実装した各コンポーネントは`src/models/components/stacked_linear/`に新しく作成して、controller, prior_encoder, observation_auto_encoderの変更を破棄してください。(Revert commit) 現在の実験を中断しないためです。(transitionの修正はOKです。ありがとうございます)

試験期間で動けなかったのでめっちゃ助かります！ありがとうございます！

2023-02-08 12:39 UTC, Geson-anko commented on src/models/components/linear_layers.py
> +            self.hidden_layers.add_module(f"ReLU_{i}",torch.nn.ReLU())
BatchNorm 1dも欲しいですね。総数を深くしたときに値の爆発を防いでくれます。

2023-02-08 12:39 UTC, Geson-anko commented on src/models/components/controller.py
> +        )
fc_meanとfc_logsは計算量の削減のためにただの線形層でお願いします
その前に`fc_hiddens`等の名前で`LinearLayer`を定義しておいて、そこから分岐させる方法を取りましょう。

LinearLayersのhidden_sizeもコンストラクタの引数から直接指定できるようにしましょう。レイヤーの数も同様です。
```suggestion
        self.fc_hiddens = LinearLayers(c_hidden_size, stacked_linear_hidden_size)
        
        self.fc_mean = nn.Linear(stacked_linear_hidden_size, action_size)
        self.fc_logs = nn.Linear(stacked_linear_hidden_size, action_size)
```

2023-02-08 12:39 UTC, Geson-anko commented on src/models/components/linear_layers.py
> +            self.hidden_layers.add_module(f"ReLU_{i}",torch.nn.ReLU())
`append`で追加できます。  
```suggestion
            self.hidden_layers.append(torch.nn.Linear(hidden_size,hidden_size,bias=bias))
            self.hidden_layers.append(torch.nn.ReLU())
```

2023-02-08 12:39 UTC, Geson-anko commented on src/models/components/observation_auto_encoder.py
> +        )
ここもfc_hidden_layersとしてまとめて、最後に`fc_mean`や`fc_logs`を通す形をとってください。そしてLinearLayersの中間層のサイズをコンストラクタで指定できるようにしてください。レイヤーの数も同様です。

2023-02-08 12:39 UTC, Geson-anko commented on src/models/components/observation_auto_encoder.py
> +        )
ここもhidden_sizeとlayersをコンストラクタで指定できるようにしましょう。

2023-02-08 12:39 UTC, Geson-anko commented on src/models/components/prior_encoder.py
> +        )
ここもcontrollerのレビューと同じくです。

2023-02-09 10:55 UTC, cehl-kurage reviewed
追加で修正のリクエストはありません

2023-02-10 15:05 UTC, cehl-kurage commented on src/models/components/linear_layers.py
> +            self.hidden_layers.append(nn.LayerNorm(hidden_size))
レビューでは`BatchNorm1d`を追加することになってましたが、この変更の理由は何でしょう？

2023-02-11 06:41 UTC, Geson-anko commented on src/models/components/linear_layers.py
> +            self.hidden_layers.append(nn.LayerNorm(hidden_size))
@cehl-kurage これは RNNに適用する関係でBatchNormが期待通り動作しないことが想定されるためです。  
BatchNormは時間軸も含めたミニバッチ全体に適用したいのですが、RNNは性質上時間方向を別々に処理するので、各タイムステップごとに正則化されてしまいます。こういった観点からLayer Normalizationを使用しました。シフトとスケールがデータごとに常に0, 1になる効果は回帰問題においてデメリットがありますが、中間出力とする分には問題ないと判断しました。

2023-02-11 06:42 UTC, Geson-anko approved these changes
コードを大きく改変したためレビュアーから辞退します

2023-02-11 06:52 UTC, merged