show imagination horizon
matsuo-group24-PinkTrombone/SpeechGeneration pull request #96
Opened 2023-02-13 13:41 UTC by cehl-kurage

## 概要
#94 

## 変更内容
- src/models/dreamer.py
- tests/models/test_dreamer.py

## 影響範囲

## Submit前の確認項目

- [ ] タイトルは一目でわかるようにし、説明文は PR を簡潔に説明するようにしましたか?
- [ ] あなたの PR が、異なる変更を束ねたものではなく、ひとつのことだけを行うものであることを確認しましたか?
- [ ] この PR で導入されたすべての変更点をリストアップしましたか?
- [ ] PR を `pytest`または `make test`コマンドでローカルにテストしましたか?
- [ ] `pre-commit run -a` または`make format`コマンドで `pre-commit` フックを実行しましたか?

## 補足

2023-02-14 08:16 UTC, Geson-anko requested changes
お疲れ様です。いい感じに実装できてきましたね。どのように実装するかの方法をしっかり擦り合わせましょう。（事前にそれをしなかったのは申し訳ないです）
1. うまくいっているか記録する処理は`evaluation_step`の最後に**全く別な処理として**付け足しましょう。既存の音声生成がうまくいっているかを記録処理が期待通り動作しなくなってしまっています。  
2. `log_spectrogram`の機能は汎用的で、他にも使え回せそうなので、独立させて、`Figure`クラスを直接返すようにし、`src/utils/figure_making.py`にでも作成しましょう。
3. エラーメッセージを消すためにテストケースを修正する行為は本質的なミスがそこにない限り絶対にやってはいけません。二度とやってはいけません。

2023-02-14 08:16 UTC, Geson-anko commented on tests/models/abc/test_dummy_classes.py
ここのassertの変更は問題の本質的な解決になっていません。エラーの原因を特定して直してください。(ちなみに今回のやり方は**正しい方を変える**という致命的な修正です。できる限りテストケースを変えてエラーメッセージを消す行為はやめてください)

2023-02-15 12:36 UTC, cehl-kurage commented
wip

2023-02-16 11:43 UTC, Geson-anko commented
@cehl-kurage ちょっと僕の環境だと演算デバイスでエラー起きちゃったので修正お願いします！`make test`が通りませんでした
```
tests/test_trainer.py::test_fit[cuda] 
--------------------------------------------------------- live log call ----------------------------------------------------------
ERROR    src.trainer:trainer.py:145 Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Traceback (most recent call last):
  File "/workspace/src/trainer.py", line 126, in fit
    loss_dict = model.evaluation_step(env)
  File "/opt/conda/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/workspace/src/models/dreamer.py", line 473, in evaluation_step
    visualize_model_approximation(
  File "/workspace/src/utils/visualize.py", line 80, in visualize_model_approximation
    action = agent.act(obs=(voc_state, generated_ref), target=target, probabilistic=False)
  File "/workspace/src/models/abc/agent.py", line 72, in act
    state = self.obs_encoder.forward(hidden, obs).sample()
  File "/workspace/src/models/abc/observation_auto_encoder.py", line 55, in forward
    embedded_obs = self.embed_observation(obs)
  File "/workspace/tests/models/abc/dummy_classes.py", line 75, in embed_observation
    return emb + (v.mean() + g.mean()) * self.dmy_w.mean()
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

2023-02-16 11:54 UTC, Geson-anko approved these changes
演算デバイスエラーは直しておきました。いくつか修正あるのでよろしくおねがいします～！

2023-02-16 11:54 UTC, Geson-anko commented on src/utils/visualize.py
> +    # init hidden for world model's prediction
内部状態のリセットを忘れずに
```suggestion
    # init hidden for world model's prediction
    agent.reset()
```

2023-02-16 11:54 UTC, Geson-anko commented on src/utils/visualize.py
> +def visualize_model_approximation(
デコレーターにするとシンプルでインデントを浅くできます。
```suggestion
@torch.no_grad()
def visualize_model_approximation(
```

2023-02-16 11:54 UTC, Geson-anko commented on src/utils/visualize.py
> +    with torch.no_grad():
`torch.no_grad()`はデコレーターにするとよいです。
```suggestion
```

2023-02-16 11:54 UTC, Geson-anko commented on src/utils/visualize.py
> +            state = world.prior(hidden).sample()
transitionモデルを使うタイミングはここです。`hidden`は初期値0となっているため直接最初の`action`と0初期化された`state`, `hidden`を使って次の意味がある隠れ状態を生成する必要があります。
```suggestion
            # append prediction by world model
            next_hidden = world.transition(hidden, state, action)
            state = world.prior(next_hidden).sample()
```

2023-02-16 11:54 UTC, Geson-anko commented on src/utils/visualize.py
> +            next_hidden = world.transition(hidden, state, action)
```suggestion
```

2023-02-16 11:54 UTC, Geson-anko commented on src/models/dreamer.py
> +        )
デバイスエラーの原因はここでした。
```suggestion
            self.current_step,
            device=self.device,
            dtype=self.dtype
        )
```

2023-02-16 11:56 UTC, Geson-anko requested changes
間違えてさっきApproveしちゃいました。Request changesです。

2023-02-16 11:56 UTC, Geson-anko commented on src/models/dreamer.py
> +            prefix + "melspectrograms",
```suggestion
            prefix + "target-generatino-imagination-spectrograms",
```

2023-02-16 13:23 UTC, cehl-kurage commented
修正箇所のテストしか実行してませんでした...！
すみません。修正ありがとうございます！

2023-02-16 15:10 UTC, Geson-anko commented on src/utils/visualize.py
> +        generated_pred_spect = np.concatenate(all_generated_pred, axis=-1)
バッチ軸の削除
```suggestion
        target_spect = np.concatenate(all_target, axis=-1).squeeze(0)
        generated_ref_spect = np.concatenate(all_generated_ref, axis=-1).squeeze(0)
        generated_pred_spect = np.concatenate(all_generated_pred, axis=-1).squeeze(0)
```

2023-02-17 04:22 UTC, cehl-kurage commented on src/utils/visualize.py
> +        generated_pred_spect = np.concatenate(all_generated_pred, axis=-1)
`target`, `generated_ref` は2次元なのでそのまま  
`generated_pred_spect` はバッチ軸を削除しました。

2023-02-17 04:35 UTC, Geson-anko commented on src/utils/visualize.py
> +            state = world.prior(hidden).sample()
@cehl-kurage 返信遅れました、actionはagentが予測したものを常に使います。

2023-02-17 06:04 UTC, Geson-anko approved these changes
おおよそ完了していたのでちょっと修正しました！マージします

2023-02-17 06:06 UTC, merged